### PR TITLE
Drop unused function `kill_port_fwd`

### PR DESCRIPTION
**Pull request by Ichimonji10**
```console
$ git grep kill_port_fwd
cicd/cji_smoke_test.sh:function kill_port_fwd {
cicd/deploy_ephemeral_db.sh:function kill_port_fwd {
```

### CODE REVIEW

**Comment by bsquizz** [comment]
I think this function *is* supposed to be called by a trap ;) Let me look.

**Comment by bsquizz** [comment]
See https://github.com/RedHatInsights/bonfire/pull/100

**Comment by bsquizz** [comment]
Ok we decided since you can't re-define a trap for the same signal, to just not bother killing the port forwards at all for now. They should die when the ephemeral env is cleaned up.

**Comment by Ichimonji10** [comment]
In case anyone is wondering what happens if you re-define a trap for a signal:

```bash
#!/usr/bin/env bash
# coding=utf-8

function teardown1 {
    echo "teardown1 is executing"
}

function teardown2 {
    echo "teardown2 is executing"
}

trap "teardown1" EXIT ERR SIGINT SIGTERM
trap "teardown2" EXIT ERR SIGINT SIGTERM
```

```console
$ ./test.sh 
teardown2 is executing
```

**Pull request merged**
