### PR TITLE
Add simple labels test

### PR DESCRIPTION
**Pull request by Victoremepunto**
This is a dummy PR to test RedHatInsights/cicd-tools#33

### CODE REVIEW

**Comment by Victoremepunto** [comment]
One can run this test with 

```
# podman
./tests/test_labels_test.sh podman tests/data labelstest.Dockerfile

# docker
./tests/test_labels_test.sh docker tests/data labelstest.Dockerfile
```

**Comment by bsquizz** [comment]
@Victoremepunto does this kind of thing belong in cicd-tools now?

**Comment by Victoremepunto** [comment]
@bsquizz  yeah this sort of thing (issues related with the "old" bonfire bootstrap scripts) goes now there - however this specific issue can be closed, I think the way it was fixed was detecting the podman version and disabling cache. 

I don't know if you can migrate issues, if you can feel free - otherwise lets just close it!

**Comment by bsquizz** [comment]
Migrated the issue to https://github.com/RedHatInsights/cicd-tools/issues/33

**Pull request closed without merging**
